### ISSUE TITLE
X0135 M005A mzkitchen 10 rumsDB table not updating GUI

### ISSUE THREAD

**Issue by ngoccalico** [eugenemel/maven#112]
Clicking around rumsDB is only updating the `compound widget` when `rumsDB` is set.  The EIC widget and the MS/MS fragmentation spectrum widget are not responding.

**Comment by PMSeitzer** [comment]
This was caused by a file being retrieved from mzkitchen, opened in `8.1.17`, saved in `8.1.17`, and reopened in `8.1.17.1`.  The saving procedure in `8.1.17` wasn't working correctly, so this didn't work.

When the same file was retrieved from mzkitchen, opened in `8.1.17.1`, saved in `8.1.17.1`, and reopened in `8.1.17.1`, updating worked appropriately.
