### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by sorenwacker** [eugenemel/maven#260]
Hi,

I am trying to find documentation of Maven, the GUI and the underlying routines. 
Could you share a link here, please?

Thanks

**Comment by PMSeitzer** [comment]
Hello,

Thanks for your interest.  In terms of documentation, I'm afraid there isn't too much right now.  We are working on a new manuscript, that will contain some description of the GUI and algorithms.

In the meantime, I can refer you to some older publications, though these are a bit out of date:

1.
```
MLA | Clasquin, Michelle F., Eugene Melamud, and Joshua D. Rabinowitz. "LC‐MS data processing with MAVEN: a metabolomic analysis and visualization engine." Current protocols in bioinformatics 37.1 (2012): 14-11.
```

2.
```
Melamud, Eugene, Livia Vastag, and Joshua D. Rabinowitz. "Metabolomic analysis and visualization engine for LC− MS data." Analytical chemistry 82.23 (2010): 9818-9826.
```

If there is a specific question you have, I would be happy to answer it.

If you are curious about algorithms, you are welcome to read the source code.  Most of the algorithms are actually in the `maven_core` repository:
https://github.com/eugenemel/maven_core

**Comment by soerendip** [comment]
I wonder how maven calculates the peak heights. When I extract the maximum value with `pyteomics` I often get slightly higher values than the values that Maven extracts. I wonder if there is an offset removed or a kind of average taken?

**Comment by PMSeitzer** [comment]
Hey @soerendip , 

I think the most likely thing that is happening is that the values returned by Maven are adjusted by subtracting a baseline from the peak height or peak area.  Alternatively, the peak value you are reading is the smoothed eic value instead of the raw value.  Both baseline computation and smoothing can be adjusted by modifying some parameters, I think you should be able to effectively disable this step by adjusting the appropriate parameters. If it isn't possible to completely disable smoothing / baseline estimation, this would be a useful thing for us to implement in the future.

I would recommend updating to the latest version if you are not already using this version (https://github.com/eugenemel/maven/releases/tag/8.1.27.6), to ensure that the discrepancy you are seeing is not due to a bug that has already been fixed.

However, to determine exactly what the issue is, would you mind providing some more detail describing your issue? 
Specificlly,
How did you read the peak height values? From an exported peaks search? From the eic widget? from a single scan? From a consensus spectrum (combination of several scans)? What version of MAVEN are you using? What raw files were you using? Did you perform a library search / peaks search? What kind of quantification did you have selectedin the drop-down menu in the main window (Area, AreaTop, Height)?

**Comment by PMSeitzer** [comment]
Waiting for feedback from @soerendip to continue work on this issue

**Comment by PMSeitzer** [comment]
We could add a tutorial for starting from nothing to analyzing data files.

**Comment by soerendip** [comment]
I have done some testing and it seems the discrepancy comes from different retention time windows. Each file somehow ends up with a specific set of rt minimum and rt maximum rather than all files are treated the same. This of course makes sense when there are significant RT drifts in the data. Though it would be nice to know exactly what fitting and smoothing steps are done by default.

**Comment by soerendip** [comment]
Do you plan to support mzML format in the future?

**Comment by PMSeitzer** [comment]
Hey @soerendip,
Glad to hear that you've done some testing and found the discrepancy.

mzML files should already be supported.  If you encounter any issues trying to import mzML files, let me know and I'll be happy to help.

**Comment by soerendip** [comment]
Oh, great. Hm, what version did I use last time that did not work. mzML totally works with EI-Maven, great!

**Comment by PMSeitzer** [comment]
Hi @sorenwacker ,

I'm happy to report that there is some new documentation for MAVEN available, associated with a new manuscript (out today):
https://www.mdpi.com/2218-1989/12/8/684/htm

If you follow the above link, there is even a video tutorial and several datasets / scripts in the supplementary materials.

**Comment by sorenwacker** [comment]
Congrats!! I will have a look.

**Comment by sorenwacker** [comment]
I wonder, which of the datasets are created in MS1 mode? Or are all using MS/MS?

**Comment by PMSeitzer** [comment]
@sorenwacker All of the datasets from the tutorial used MS/MS. I'm working with Metabolights now to finalize the availability of the mzXML/mzML files, hopefully they should be available soon

**Comment by sorenwacker** [comment]
Sorry, to bother you here. I just wonder why did you not include a MS1 example anymore? Do you think most groups are interested in MS/MS workflows nowadays? I have been in discussion about that with a few people and I am interested in your opinion on that topic.

**Comment by PMSeitzer** [comment]
No Problem @sorenwacker.  The manuscript focused especially on MS/MS analysis, so the tutorials/examples/analyses were geared towards highlighting that.  Many of the tools/features would still work for MS1 only, though - e.g., peak picking, peak grouping, identifying compounds based on precursor m/z and possibly RT.  I think much of the GUI functionality should still be useful for MS1 only analysis (EIC widget, MS1 scan visualization, etc).
If there is good demand for it, I'd be happy to make a tutorial for MS1-only data.  Feel free to reach out also if you have any specific questions.

**Comment by sorenwacker** [comment]
Thank you.
