### ISSUE TITLE
MAVEN Crashes when picking peak on large metabolomics dataset

### ISSUE THREAD

**Issue by kukurugya** [eugenemel/maven#35]
MAVEN version 8.0.21

Opened dataset --> loaded libraries --> picked ~4 peaks before it crashed. This is happening very frequently with larger datasets. 

![Screen Shot 2019-07-19 at 4 13 37 PM](https://user-images.githubusercontent.com/29959207/61570306-9838d100-aa40-11e9-9eb4-c38d97161c66.png)

**Comment by kukurugya** [comment]
Dataset - X110-M001A 
Libraries - everything for method M001A TBA

**Comment by PMSeitzer** [comment]
The problem was that the library `Compound->frag_mzs` and `Compound->frag_intensities` were not the same size, b/c some intensities were being stored in the database as the string`0.00000`.  Then, `QString.toDouble()` returns the double value `0.0`, which is also overloaded as `QString.toDouble()` conversion failed, and these intensity values are skipped.

This has been corrected in the database by manually avoiding writing strings to the database if they are exactly `0.00000`.  If `Compound->frag_mzs` and `Compound-frag_intensities` are ever not equal, the program immediately crashes with an error message explaining that this is the cause of the crashes (crash is executed using `abort()`.
