### ISSUE TITLE
Can not open the MAVEN software on Window system

### ISSUE THREAD

**Issue by HuanLab** [eugenemel/maven#505]
Hi,

I have rencently tried to use MAVEN for some data processing but found the exe file couldn't be opened. The interface would pop up for a sec before vanishing. It happened very fast so I took a screenshot of it as below. Could you help me out on how to make it work? Thanks.
![MAVEN](https://user-images.githubusercontent.com/52514403/140420665-a63ba27e-5fe4-4530-930b-79e2b45ddceb.JPG)

**Comment by PMSeitzer** [comment]
Hi @HuanLab ,
Thanks for opening the ticket. I actually encountered the same bug recently: #499 

The issue is in the tool we use to deploy the maven executable (called `AppVeyor`).  The specific problem is the `qsqlite.dll` file appears to somehow be malformed in the latest build.

For now, you can fix the issue by

(1) Downloading MAVEN version `8.1.27.31`
(2) Replacing the `qsqlite.dll` file from version`8.1.28.8` folder with the `qsqlite.dll` file from version `8.1.27.31` (this file should be about ~1300 kB)

You can see screenshots and more discussion in #499

**Comment by PMSeitzer** [comment]
Hi @HuanLab, were you able to get it to work?

**Comment by HuanLab** [comment]
It worked. Thanks!
