### ISSUE TITLE
Implement peak quant options based on smoothed measurements

### ISSUE THREAD

**Issue by PMSeitzer** [eugenemel/maven#603]
e.g., `smoothedPeakAreaTop`, `smoothedArea`, `smoothedAreaCorrected` etc.

**Comment by cmsand** [comment]
Representative unsmoothed peak below. Because of peak shape noise around apex, quantification by `Area` gives better CVs on replicate injections than `Area Top` for unsmoothed peaks. Because of this data should be reported as peak `Area` until smoothing implemented.

![Screenshot 2022-12-16 at 10 58 01 AM](https://user-images.githubusercontent.com/9013133/208169495-578c4e7d-98a4-4966-ae51-3def650ffa99.png)

**Comment by PMSeitzer** [comment]
This was requested again as part of QQQ work.

**Comment by PMSeitzer** [comment]
After adding fields to `Peak` class (`mzSample.h`), update `EIC::getPeakDetails()` (`EIC.cpp`) with the new computations.

**Comment by PMSeitzer** [comment]
Given the big change to the database, this should be on its own feature branch, just to isolate any issues that might occur with compatibility.

**Comment by PMSeitzer** [comment]
This can be completed as part of #549, in the `issue-549` feature branch.
