### ISSUE TITLE
Isotope Bar Plot Visibility Issues

### ISSUE THREAD

**Issue by ddlidded** [eugenemel/maven#761]
The last few versions that were released seemed to have broken the isotope bar display feature. When toggled it does not show up at all and no longer works. Can someone please advise on how to fix this issue or if this is a potential bug?

Version: 2.10.19

Thanks!

![image](https://github.com/user-attachments/assets/fd37152f-e110-455e-83b8-705467e38f91)

**Comment by PMSeitzer** [comment]
@ddlidded Thanks so much for letting me know - I added this ticket to the latest milestone, will take a look soon.
In the mean time, are the other isotope extraction algorithms still working? this might be something that is affecting the `MAVEN_ONE` algorithm only.

<img width="1111" alt=" MAVEN_isotopes_options" src="https://github.com/user-attachments/assets/73e257a3-af85-4114-8381-ee86474feae0">

**Comment by PMSeitzer** [comment]
@ddlidded I wasn't able to reproduce your issue - could you provide some more information? If you're able to share mzML files / msp files, please send them to maven2software [at ] gmail

**Comment by PMSeitzer** [comment]
@ddlidded I was able to reproduce your issue in some other datasets, and I think the issue has to do with the isotopic extraction algorithm - it appears that no isotopes are detected with your parameter set, which is why the plot shows no values. If you change, for example, to `[M+0] Full Width Integration`, you should definitely see some isotopes. If you still don't, let me know and I can take a deeper look.

**Comment by ddlidded** [comment]
@PMSeitzer Well I can open the files in El-Maven with no labeling issue, and my set indeed does have labeling which is supported by El-Maven as well. So I don't understand why their package has no issues when it comes to labels, but the new maven versions do. I see this across the board on multiple computers. This was never an issue before and we have not done anything differently so its perplexing.
